---
title: "EDA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(ggplot2)
library(MASS)
library(knitr)
library(dplyr)
library(tidyr)
library(tibble)
library(tidyverse)
library(caret)
library(cowplot)
library(PerformanceAnalytics) #correlation matrix
library(randomForest)
library(broom)
library(glmmTMB)
library(kableExtra)
```

```{r}
data <- read.csv("complete_project_data.csv")
```

```{r,out.height = '100%', out.width = '100%', fig.show= 'hold', fig.align='center'}
labels <- c("0" = "NOT A HIT SONG", "1" = "HIT SONG")
p1 <- ggplot(data, aes(x = Acousticness)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Acousticness", x = "Acousticness", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

p2 <- ggplot(data, aes(x = Danceability)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Danceability", x = "Danceability", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

p3 <- ggplot(data, aes(x = Energy)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Energy", x = "Energy", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

p4 <- ggplot(data, aes(x = Loudness)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Loudness", x = "Loudness", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

p5 <- ggplot(data, aes(x = Speechiness)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Speechiness", x = "Speechiness", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

p6 <- ggplot(data, aes(x = Instrumentalness)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Instrumentalness", x = "Instrumentalness", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

p7 <- ggplot(data, aes(x = Liveness)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Liveness", x = "Liveness", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

p8 <- ggplot(data, aes(x = Valence)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Valence", x = "Valence", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")


p9 <- ggplot(data, aes(x = Tempo)) +
  geom_histogram(aes(color = Label, fill = Label),
                position = "identity", bins = 30) +
    facet_wrap(~ Label, scales = "free_x", ncol = 5, labeller=labeller(Label = labels)) + labs(title = "Distribution of Tempo", x = "Tempo", y = "Count") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (8)), axis.title = element_text(family = "Helvetica", size = (6)))+ theme(legend.position = "none")

plot_grid(p1, p2,p3, p4,p5, p6,p7, p8,p9)
```
```{r, out.height = '49%', out.width = '49%', fig.show= 'hold', fig.align='center'}
data$ArtistScore <- as.factor(data$ArtistScore)
data$Label <- as.factor(data$Label)

ArtistScore <- c("0","1")
hit <- c("NOT A HIT SONG","NOT A HIT SONG","HIT SONG","HIT SONG")
values <- c(sum(data$ArtistScore == "0" & data$Label == "0"),
            sum(data$ArtistScore == "1" & data$Label == "0"),
            sum(data$ArtistScore == "0" & data$Label == "1"),
            sum(data$ArtistScore == "1" & data$Label == "1"))

ArtistScore_data <- data.frame(ArtistScore,hit,values)
ggplot(ArtistScore_data, aes(fill=hit, y=values, x=ArtistScore)) + 
    geom_bar(position="fill", stat="identity") + labs(title = "Proportion of Hit Songs Based on the Artist Score", x = "Artist Score", y = "Proportion") + theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (15)), axis.title = element_text(family = "Helvetica", size = (12))) + theme(legend.title = element_blank())
```

